[package]
name = "rgb-term"
version = "0.1.0"
authors = ["YourFin <d.junkpobox+git@gmail.com>", "[PUT YO NAME HERE]"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
